import { PRICE_PREVIEW_MESSAGE, type NoirProduct } from "@/lib/medusa/types"

const common = {
  lockedPrice: PRICE_PREVIEW_MESSAGE,
  imagePlaceholder: "linear-gradient(to bottom right, #171512, #050403)",
  reserveStatus: "Available to order",
  releaseStatus: "Lot 1 preview",
  stock: null,
  isPrivate: true,
  source: "fallback" as const,
  // Fallback products power the local/demo storefront when Medusa is not
  // configured. Keep them purchasable so the normal cart journey is testable.
  availableForSale: true,
}

export const fallbackProducts: NoirProduct[] = [
  {
    ...common,
    id: "dark-chocolate-almonds",
    slug: "dark-chocolate-coated-almonds",
    name: "Dark Chocolate Coated Almonds",
    category: "Coated Almonds",
    badge: "Pure Couverture",
    batchCode: "DC-001",
    batchNumber: "LOT 1 / DC-001",
    finish: "Dark chocolate coating",
    texture: "Crunchy roasted almonds with a crisp chocolate shell",
    packaging: "Matte black gift insert",
    weight: "180 g",
    status: "Member Preview",
    shortDescription: "Crunchy roasted almonds coated in rich dark chocolate.",
    longDescription: "Crunchy roasted almonds coated in rich dark couverture chocolate with a light cocoa finish.",
    price: "₹899",
    images: ["/images/products/dark-chocolate-almonds.png"],
    storage: "Store cool and dry, away from direct sunlight",
    pairing: "Espresso, black tea, or after-dinner service",
    giftingUse: "Premium table gift or client box",
    ingredientNote: "Roasted almonds, dark couverture chocolate and cocoa.",
    sensory: {
      see: "Satin cocoa finish with a soft, even sheen",
      touch: "Polished shell around a firm almond centre",
      aroma: "Dark cocoa and warm roasted almond",
      sound: "A clean shell snap followed by almond crunch",
      taste: "Deep couverture, roasted almond and restrained sweetness",
    },
    isFeatured: true,
  },
  {
    ...common,
    id: "milk-chocolate-almonds",
    slug: "milk-chocolate-coated-almonds",
    name: "Milk Chocolate Coated Almonds",
    category: "Coated Almonds",
    badge: "Signature Coated",
    batchCode: "MC-001",
    batchNumber: "LOT 1 / MC-001",
    finish: "Milk chocolate coating",
    texture: "Crunchy roasted almonds with a smooth chocolate shell",
    packaging: "Matte black gift insert",
    weight: "180 g",
    status: "Member Preview",
    shortDescription: "Roasted almonds coated in a smooth milk chocolate shell.",
    longDescription: "Crunchy roasted almonds covered in smooth milk chocolate for an easy, balanced bite.",
    price: "₹849",
    images: ["/images/products/milk-chocolate-almonds.png"],
    storage: "Store cool and dry, away from direct sunlight",
    pairing: "Oolong tea, cappuccino, or an evening tasting plate",
    giftingUse: "Host gift or client thank-you box",
    ingredientNote: "Roasted almonds and smooth milk chocolate coating.",
    sensory: {
      see: "A soft gloss across the rounded chocolate shell",
      touch: "Smooth coating with a firm centre",
      aroma: "Milk chocolate and freshly roasted almond",
      sound: "A gentle shell break and crisp almond bite",
      taste: "Creamy cocoa followed by roasted almond",
    },
    isFeatured: true,
  },
  {
    ...common,
    id: "parmesan-makhana",
    slug: "parmesan-cheese-makhana",
    name: "Parmesan Cheese Makhana",
    category: "Makhana Tins",
    badge: "Gold-Sealed Tin",
    batchCode: "PM-001",
    batchNumber: "LOT 1 / PM-001",
    finish: "Savoury parmesan-style seasoning",
    texture: "Light crisp jumbo makhana",
    packaging: "Gold-sealed black tin",
    weight: "70 g",
    status: "Member Preview",
    shortDescription: "Jumbo makhana finished with a savoury parmesan-style seasoning.",
    longDescription: "Light, crunchy makhana with a savoury parmesan-style seasoning, packed in a black tin.",
    price: "₹599",
    images: ["/images/products/chocolate-makhana.png"],
    storage: "Reseal after opening and keep cool and dry",
    pairing: "Sparkling water, aperitif service, or a cheese board",
    giftingUse: "Premium table gift or festive hamper",
    ingredientNote: "Jumbo makhana with parmesan-style savoury seasoning.",
    sensory: {
      see: "Fine savoury seasoning over pale roasted makhana",
      touch: "Dry, light surface with an airy centre",
      aroma: "Warm roasted makhana and savoury cheese notes",
      sound: "A light, clean crunch when opened and tasted",
      taste: "Rounded parmesan-style seasoning with a roasted finish",
    },
    isFeatured: true,
  },
  {
    ...common,
    id: "pink-salt-makhana",
    slug: "himalayan-pink-salt-makhana",
    name: "Himalayan Pink Salt Makhana",
    category: "Makhana Tins",
    badge: "Gold-Sealed Tin",
    batchCode: "HM-001",
    batchNumber: "LOT 1 / HM-001",
    finish: "Himalayan pink salt seasoning",
    texture: "Slow-roasted crisp makhana",
    packaging: "Gold-sealed black tin",
    weight: "70 g",
    status: "Member Preview",
    shortDescription: "Slow-roasted makhana with a restrained Himalayan pink salt seasoning.",
    longDescription: "Light, crunchy makhana with a simple Himalayan pink salt seasoning.",
    price: "₹549",
    images: ["/images/products/pink-salt-makhana.png"],
    storage: "Reseal after opening and keep cool and dry",
    pairing: "Dry white wine, sparkling water, or a pre-dinner table",
    giftingUse: "Host gift or premium table tin",
    ingredientNote: "Jumbo makhana, Himalayan pink salt seasoning and roasting medium.",
    sensory: {
      see: "A fine mineral dusting on slow-roasted makhana",
      touch: "Dry exterior with an airy centre",
      aroma: "Warm roasted makhana",
      sound: "A clean tin opening and light crisp bite",
      taste: "Roasted makhana with a measured pink salt finish",
    },
    isPrivate: false,
    isFeatured: false,
  },
  {
    ...common,
    id: "curated-collection-box",
    slug: "curated-collection-box",
    name: "The Curated Collection Box",
    category: "Gift Boxes",
    badge: "Numbered Lot 1",
    batchCode: "GB-001",
    batchNumber: "LOT 1 / GB-001",
    finish: "Mixed member preview collection",
    texture: "Chocolate shell, crisp makhana, roasted nut finish",
    packaging: "Magnetic rigid box with velvet-inspired insert",
    weight: "Assorted",
    status: "Available",
    shortDescription: "A gift box with chocolate almonds and makhana in a magnetic black box.",
    longDescription: "A gift-ready mix of chocolate almonds and makhana, presented in a matte black magnetic box with a numbered batch card.",
    price: "₹2,499",
    images: ["/images/products/curated-collection-box.png"],
    storage: "Keep the contents cool and dry; retain tins sealed until serving",
    pairing: "After-dinner table, boardroom service, or a festive gathering",
    giftingUse: "Corporate gifting, festive gifting, or a limited box reservation",
    ingredientNote: "Assorted Lot 1 coated almonds and seasoned makhana; see individual pack labels.",
    sensory: {
      see: "Matte black surfaces, a gold seal and a numbered insert",
      touch: "Rigid magnetic box with a velvet-inspired interior",
      aroma: "Cocoa, roasted almond and warm savoury seasoning",
      sound: "Magnetic closure, tin opening and layered crisp bites",
      taste: "A progression from couverture to parmesan and pink salt",
    },
    isFeatured: true,
  },
  {
    ...common,
    id: "signature-almond-duo",
    slug: "signature-almond-duo",
    name: "The Signature Almond Duo",
    category: "Gift Boxes",
    badge: "Member Preview",
    batchCode: "AD-001",
    batchNumber: "LOT 1 / AD-001",
    finish: "Dark and milk chocolate almond pairing",
    texture: "Crisp almond centre with polished shell",
    packaging: "Dual matte black gift insert",
    weight: "Assorted",
    status: "Member Preview",
    shortDescription: "Dark and milk chocolate almonds in one gift-ready box.",
    longDescription: "Dark chocolate almonds and milk chocolate almonds together in a matte black gift box.",
    price: "₹1,599",
    images: ["/images/products/signature-almond-duo.png"],
    storage: "Store cool and dry, away from direct sunlight",
    pairing: "Serve dark and milk batches side by side with coffee or tea",
    giftingUse: "Client thank-you box or host gift",
    ingredientNote: "Dark couverture coated almonds and milk chocolate coated almonds.",
    sensory: {
      see: "A contrast of satin cocoa and milk chocolate gloss",
      touch: "Smooth shells set into a rigid dual insert",
      aroma: "Dark cocoa, milk chocolate and roasted almond",
      sound: "Two distinct shell snaps over a crisp centre",
      taste: "A side-by-side dark and milk chocolate tasting",
    },
    isFeatured: false,
  },
]

export function getFallbackProductBySlug(slug: string) {
  return fallbackProducts.find((product) => product.slug === slug) || null
}
